// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29QXZDOgpVWDr7gfo8_a1xLPYLI_7TQE',
    appId: '1:889463869810:android:164cca8f1e7ad4654b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Z4aYJUgVqFUPoVyqGfIFyRrlEzu3gUk',
    appId: '1:889463869810:ios:27bdb7f4a50562a54b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
    iosBundleId: 'com.example.builtBetterApp',
  );
}
