name: Deploy Flutter Web to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Enable manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Run tests
      - name: Run tests
        run: flutter test
      
      # Build web
      - name: Build web
        run: flutter build web --release
      
      # Deploy to Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: bbm-db-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
